In [1]:
# Zur Nutzung der api für die Datenbank Genesis Online benötigen Sie einen kostenfreien Account
# hier registrieren falls noch nicht geschehen
# https://www-genesis.destatis.de/genesis/online?Menu=RegistrierungForm&REGKUNDENTYP=001

In [1]:
# Tragen Sie hier Ihre Zugangsdaten für die Datenbank Genesis Online des Statistischen Bundesamtes ein
KENNUNG="xxx"
PASSWORT="xxx"

In [3]:
# Monatliches update 
# aktualisiert die csv-Datei für eine D3 Spiral Heatmap

In [4]:
import pandas as pd

In [5]:
pd.options.mode.chained_assignment = None  # default='warn'

In [13]:
# Download der Tabelle als Flatfile-csv 
df73421_0002 = pd.read_csv("https://www-genesis.destatis.de/genesisWS/rest/2020/data/tablefile?username="+KENNUNG+"&password="+PASSWORT 
                      +"&name=73421-0002&startyear=1993&format=ffcsv", dtype=str, sep=';') 
                        # csv files per api are utf-8 encoded
df73421_0002

,Statistik_Code,Statistik_Label,Zeit_Code,Zeit_Label,Zeit,1_Merkmal_Code,1_Merkmal_Label,1_Auspraegung_Code,1_Auspraegung_Label,2_Merkmal_Code,2_Merkmal_Label,2_Auspraegung_Code,2_Auspraegung_Label,ABS011__Absatz_von_Bier__hl,ABS012__Absatz_von_Biermischungen__hl,ABS013__Versteuerter_Bierabsatz__hl,ABS014__Steuerfreier_Bierabsatz__hl,ABS015__Steuerfreier_Bierabsatz_in_EU-Laender__hl,ABS016__Steuerfreier_Bierabsatz_in_Drittlaender__hl,ABS017__Steuerfreier_Bierabsatz_als_Haustrunk__hl
0,73421,Biersteuerstatistik,JAHR,Jahr,1993,DINSG,Deutschland insgesamt,DG,Deutschland,MONAT,Monate,MONAT01,Januar,7040763,-,6637012,403751,220145,153662,29943
1,73421,Biersteuerstatistik,JAHR,Jahr,1993,DINSG,Deutschland insgesamt,DG,Deutschland,MONAT,Monate,MONAT02,Februar,7570767,-,7142314,428452,208869,189993,29590
2,73421,Biersteuerstatistik,JAHR,Jahr,1993,DINSG,Deutschland insgesamt,DG,Deutschland,MONAT,Monate,MONAT03,März,9055530,-,8519306,536224,269589,235071,31564
3,73421,Biersteuerstatistik,JAHR,Jahr,1993,DINSG,Deutschland insgesamt,DG,Deutschland,MONAT,Monate,MONAT04,April,10069359,-,9406587,662771,377792,250970,34008
4,73421,Biersteuerstatistik,JAHR,Jahr,1993,DINSG,Deutschland insgesamt,DG,Deutschland,MONAT,Monate,MONAT05,Mai,10560663,-,9903337,657325,342455,282389,32480
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
343,73421,Biersteuerstatistik,JAHR,Jahr,2021,DINSG,Deutschland insgesamt,DG,Deutschland,MONAT,Monate,MONAT08,August,7857928,436791,6454697,1403232,705357,688627,9248
344,73421,Biersteuerstatistik,JAHR,Jahr,2021,DINSG,Deutschland insgesamt,DG,Deutschland,MONAT,Monate,MONAT09,September,7428551,329538,6020761,1407789,596467,801979,9344
345,73421,Biersteuerstatistik,JAHR,Jahr,2021,DINSG,Deutschland insgesamt,DG,Deutschland,MONAT,Monate,MONAT10,Oktober,6408274,228901,5280394,1127880,501064,618156,8661
346,73421,Biersteuerstatistik,JAHR,Jahr,2021,DINSG,Deutschland insgesamt,DG,Deutschland,MONAT,Monate,MONAT11,November,6518149,210478,5409193,1108955,521986,577708,9261
347,73421,Biersteuerstatistik,JAHR,Jahr,2021,DINSG,Deutschland insgesamt,DG,Deutschland,MONAT,Monate,MONAT12,Dezember,...,...,...,...,...,...,...

In [14]:
bierabsatz = df73421_0002[["Zeit", "2_Auspraegung_Code", "ABS011__Absatz_von_Bier__hl"]]

In [8]:
# Monate ohne Angabe abfiltern (typischerweise Rest des laufenden Jahres)            
bierabsatz = bierabsatz.loc[bierabsatz["ABS011__Absatz_von_Bier__hl"]!="..."]

In [15]:
# Datums-Objekt im Format D/MM/YYYY erzeugen 
bierabsatz["date"] = "1/"+bierabsatz["2_Auspraegung_Code"].str[5:7] +"/"+ bierabsatz["Zeit"].astype(str)

In [18]:
# Spaltenüberschriften für den csv-Output verkürzen
output = bierabsatz.drop(columns=["Zeit","2_Auspraegung_Code"]).rename(columns={"ABS011__Absatz_von_Bier__hl" : "bierabsatz"})

In [19]:
output

    bierabsatz       date
0      7040763  1/01/1993
1      7570767  1/02/1993
2      9055530  1/03/1993
3     10069359  1/04/1993
4     10560663  1/05/1993
..         ...        ...
343    7857928  1/08/2021
344    7428551  1/09/2021
345    6408274  1/10/2021
346    6518149  1/11/2021
347        ...  1/12/2021

[348 rows x 2 columns]

In [20]:
output.to_csv("bierabsatz.csv", index=False)